### ISSUE TITLE
Plugin won't work when another block with display property is present

### ISSUE THREAD

**Issue by wazaraki** [kristerkari/stylelint-declaration-block-no-ignored-properties#7]
Detection of ignored properties stops working as soon as there is another block in the same file which contains a `display` property (with any value, doesn't matter). 

**Version:** 1.0.1

**Test case:**

```css
/* styles.css */
.a {
  display: inline;
  width: 100%; /* <- stylelint should complain about this but doesn't */
}

.b {
  display: xxxx; /* <- this causes the issue */
}
```
