### ISSUE TITLE
Violation with implicit values of element e.g. `span` + `width`

### ISSUE THREAD

**Issue by robole** [kristerkari/stylelint-declaration-block-no-ignored-properties#73]
Currently the block below is not a violation:

```css
span {
  width: 50px;
}
```

It would  be nice to make it a violation the same as:

```css
span {
  display:inline;
  width: 50px;
}
```

Are you willing to take a PR? I could take a look at it to see how it might work
